# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'confirm.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from camera import *
from PyQt5 import QtSql
from PyQt5.QtSql import QSqlDatabase
import config

#global verified_status
class Ui_MainWindow(object):
    
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("QWidget#dwidget{background-color:qlineargradient(spread:pad, x1:0.091, y1:0.0738636, x2:1, y2:1, stop:0.278409 rgba(135, 182, 165, 255), stop:1 rgba(255, 255, 255, 255));}")
        self.dwidget = QtWidgets.QWidget(MainWindow)
        self.dwidget.setObjectName("dwidget")
        
        # Creating image label to display photo
        self.imglabel = QtWidgets.QLabel(self.dwidget)
        self.imglabel.setGeometry(QtCore.QRect(200, 20, 431, 400))
        self.imglabel.setFrameShape(QtWidgets.QFrame.Panel)
        self.imglabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.imglabel.setPixmap(QtGui.QPixmap("C:\\Users\\Azamat Musaev\\Desktop\\FaceApp_3.0\\application_data\\input_image\\input_image.jpg"))
        self.imglabel.setObjectName("imglabel")
        
        # Creating question label askin whether it's you or not
        self.questionlabel = QtWidgets.QLabel(self.dwidget)
        self.questionlabel.setGeometry(QtCore.QRect(220, 410, 381, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.questionlabel.setFont(font)
        self.questionlabel.setFrameShape(QtWidgets.QFrame.Panel)
        self.questionlabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.questionlabel.setText(config.verified_status)
        self.questionlabel.setObjectName("questionlabel")
        
        # Yes btn
        self.yesbtn = QtWidgets.QPushButton(self.dwidget)
        self.yesbtn.setGeometry(QtCore.QRect(260, 490, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.yesbtn.setFont(font)
        self.yesbtn.setObjectName("yesbtn")
        self.yesbtn.clicked.connect(self.yesbtn_clicked)
        
        
        self.nobtn = QtWidgets.QPushButton(self.dwidget)
        self.nobtn.setGeometry(QtCore.QRect(430, 490, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.nobtn.setFont(font)
        self.nobtn.setObjectName("nobtn")
        self.nobtn.clicked.connect(self.nobtn_clicked)
        
        MainWindow.setCentralWidget(self.dwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
    def yesbtn_clicked(self):
        self.questionlabel.setText("You are marked as attended")
        self.update()
        db = QSqlDatabase("QPSQL")
        db.setUserName("postgres")  
        db.setPassword("postgres")
        db.setDatabaseName("universitydb")

        print(config.verified_status)
        if not db.open():
            print("Unable to connect.")
            print('Last error', db.lastError().text())
            sys.exit(1)
        
        query = QtSql.QSqlQuery(db)
        print(query.exec("SELECT * from attendance where stud_id = '" + config.verified_status + "';"))
        print(query.size())
        if query.size() == 0 or query.size() == -1:
            query.exec("INSERT INTO attendance VALUES (1,0,'" +config.verified_status +"');")
            print('Last error', db.lastError().text())
            print("inserted")
        else:
            query.exec("UPDATE table_name SET present = present+1 WHERE stud_id ='" +config.verified_status +"');")
            print('Last error', db.lastError().text())
            print("updated")
   
        
    def nobtn_clicked(self):
        self.questionlabel.setText("Try again")
        self.update()
        
    def update(self):
        self.questionlabel.adjustSize()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.yesbtn.setText(_translate("MainWindow", "YES"))
        self.nobtn.setText(_translate("MainWindow", "NO"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
